name: Frontend CI

on:
  push:
    branches: [ "dev", "main" ]
    paths: [ "**", ".github/workflows/frontend.yml" ]
  pull_request:
     branches: [ "dev", "main" ]
     paths: [ "**", ".github/workflows/frontend.yml" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Or the versions you want to test against

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # Checkout backend repo
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: fant-orangen/idatt2106_2025_03_backend
          path: backend

      # Setup Java for backend
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build backend (assume Maven wrapper and backend in backend/backend)
      - name: Build backend
        run: ./mvnw clean install
        working-directory: backend/backend

      - name: Start backend
        run: ./mvnw spring-boot:run &
        working-directory: backend/backend

      # Wait for backend to be ready
      - name: Wait for backend
        run: npx wait-on http://localhost:8080/actuator/health

      - name: Build
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm run test:unit -- --run

      # Run E2E Tests (uncomment and use)
      - name: Run E2E Tests
        run: npm run test:e2e
