name: Frontend CI

on:
  push:
    branches: [ "dev", "main" ]
    paths: [ "**", ".github/workflows/frontend.yml" ]
  pull_request:
     branches: [ "dev", "main" ]
     paths: [ "**", ".github/workflows/frontend.yml" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Or the versions you want to test against

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm run test:unit -- --run

      # Uncomment the following when E2E tests are ready
      # - name: Run E2E Tests
      #   run: npm run test:e2e
