name: Frontend CI

on:
  push:
    branches: [ "dev", "main" ]
    paths: [ "**", ".github/workflows/frontend.yml" ]
  pull_request:
    branches: [ "dev", "main" ]
    paths: [ "**", ".github/workflows/frontend.yml" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ] # <-- Consider simplifying to one Node version for now

    steps:
      - uses: actions/checkout@v4

      # +++ Add PNPM setup +++
      - uses: pnpm/action-setup@v3
        with:
          version: 8 # Or 9, or your preferred version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # +++ Change cache to pnpm +++

      # +++ Use pnpm install (will create pnpm-lock.yaml if not present) +++
      - run: pnpm install --frozen-lockfile # Use --frozen-lockfile for CI reliability

      # +++ Use pnpm run +++
      - run: pnpm run build --if-present
      - run: pnpm run test:unit -- --run
      # - run: pnpm run test:e2e
